---
- name: Add Nginx Repository
  apt_repository:
    repo: "ppa:ondrej/nginx"

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove default site
  file: path={{item}} state=absent
  with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"


- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service

- name: Copy site file
  copy:
    src: wordpress
    dest: "/etc/nginx/sites-available/wordpress"
  notify: restart nginx service

- name: Make site enabled
  file:
    src: "/etc/nginx/sites-available/wordpress"
    dest: "/etc/nginx/sites-enabled/wordpress"
    state: link
  notify: restart nginx service
