---
- name: Add Nginx Repository
  apt_repository:
    repo: "ppa:ondrej/php"

- name: install PHP
  become: true
  apt: name={{item}} state=present
  with_items:
      - php8.3-fpm
      - php8.3-common
      - php8.3-mysql
      - php8.3-xml
      - php8.3-intl
      - php8.3-curl
      - php8.3-gd
      - php8.3-imagick
      - php8.3-cli
      - php8.3-dev
      - php8.3-imap
      - php8.3-mbstring
      - php8.3-opcache
      - php8.3-redis
      - php8.3-soap
      - php8.3-zip
- name: Configure PHP FPM www.conf
  copy:
    src: www.conf
    dest: /etc/php/8.3/fpm/pool.d/www.conf
    backup: yes
  notify: restart php fpm service

- name: Configure PHP FPM php.ini
  copy:
    src: php.ini
    dest: /etc/php/8.3/fpm/php.ini
    backup: yes
  notify: restart php fpm service

